name: Generate READMEs

on:
  push:
    paths:
      - 'solutions/**'

jobs:
  updateChallengeREADMEs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install node dependencies
        run: npm install --prefix ./scripts
      
      
      - name: Remove deleted challenges from json
        run: | 
          for challenge in $(jq -r '.challengesCompleted | keys[]' scripts/challengeSummary.json) # for each challenge in the json
          do
            if test ! -d "solutions/$challenge" # if there's no challenge directory
            then
              echo "removing $challenge"
              node scripts/removeChallenge.js $challenge
            fi
          done
      
      
      - name: Generate Challenge READMEs
        run: |
          # for each challenge directory
          for directory in $(ls -d solutions/* | cut -d / -f2)
          do
            # if the challenge does not have a README
            if ! test -f "solutions/$directory/README.md"
            then
              echo "building README for $directory"
              node scripts/saveChallengeData.js $directory
              node scripts/buildChallengeReadme.js $directory
            fi
            
            # if the only file in the challenge directory is a README (there are no challenge solutions)
            if test $(ls solutions/$directory | wc -l) -eq "1" && $(test -f "solutions/$directory/README.md")
            then
              echo "removing $directory"
              rm -r solutions/$directory
              node scripts/removeChallenge.js $directory
            fi
          done
      
      
      - name: Update main challenge table
        run: node scripts/buildRepoReadme.js
      
      - name: Push changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]
          then
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add .
            git commit -m "Auto-generate README.md"
            git push
          fi
